# Generated by Django 5.0.7 on 2024-07-20 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WandVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='wands/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('EL', 'ELM'), ('CH', 'CHERRY'), ('AL', 'ALDER'), ('CN', 'CHESTNUT')], max_length=2)),
            ],
        ),
    ]
