# Generated by Django 5.0.7 on 2024-07-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellatrix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wandvariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
