# Generated by Django 5.0.7 on 2024-07-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellatrix', '0002_wandvariety_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wandvariety',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
